version: 1
update_configs:
  - package_manager: javascript
    directory: /web
    update_schedule: daily
    automerged_updates:
      - match:
          dependency_type: all
          update_type: semver:minor
